<?php

/**
 * Global Configuration File
 *
 * Setup communication variables for server & database. 
 * Also include the neccesary global variables, classes and functions.
 *
 * @author     Reinier Gombert
 * @date       16-nov-2016
 * @category   Config-file
 */
// database configuration
define('DB_HOST', "localhost");
define('DB_USER', "muziektherapie");
define('DB_PASS', "Mz_ht201");
define('DB_NAME', "muziektherapie");

// log errors
ini_set("log_errors", 'On');
ini_set("error_log", $_SERVER["DOCUMENT_ROOT"] . "/logs/php-error.log");
// error displaying
ini_set('error_reporting', E_ALL);
error_reporting(E_ALL);
ini_set('display_errors', 'On');
ini_set('display_startup_errors', 'On');

// Set Timezone
date_default_timezone_set('Europe/Amsterdam');

/**
 * CLASSES
 * 
 * This method defines the path to the classes folder
 * 
 * @param String $className     the correspondig className, automatically generated by PHP itself
 */
function myAutoloader($className)
{
    $path = $_SERVER['DOCUMENT_ROOT'] . '/include/classes/';

    include $path . 'cls.' . $className . '.php';
}

// autoload undeclared classes in runtime
spl_autoload_register('myAutoloader');

// include functions
//require_once($_SERVER['DOCUMENT_ROOT'] . "/include/functions/fnc.functions.php");

// include phpMailer
//require_once($_SERVER['DOCUMENT_ROOT'] . "/phpmailer/PHPMailerAutoload.php");

session_start();
